print("Hello world")
print("Hello world")
print("Hello world")
print("Hello world")
print("Hello world")
print("I.. I'm sejuti akter swapna. I'm a student")
print("My age is 21")
print("I have a husband")
print("My husband name is khalid mim muzahid")
print("He is a software engineer")
print("He is my hero")
print("I love him sooo much.")